apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-v1
  labels:
    app: api-gateway
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.name }}
      version: v1
  template:
    metadata:
      labels:
        app: api-gateway
        version: v1
    spec:
      containers:
      - name: api-gateway
        image: khaale/grpc-demo-api-gateway
        imagePullPolicy: IfNotPresent #Always
        ports:
        - containerPort: 5000